-- MySQL Script generated by MySQL Workbench
-- Fri May 27 13:13:09 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema portfolio
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `portfolio` ;

-- -----------------------------------------------------
-- Schema portfolio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portfolio` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `portfolio` ;

-- -----------------------------------------------------
-- Table `portfolio`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`persona` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`persona` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(50) NULL,
  `titulo` VARCHAR(50) NULL,
  `direccion` VARCHAR(200) NULL,
  `sobremi` VARCHAR(2000) NULL,
  `fotoPerfil` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`educacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`educacion` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`educacion` (
  `idEdu` INT NOT NULL,
  `tituloEdu` VARCHAR(100) NULL DEFAULT NULL,
  `anioEdu` INT NULL DEFAULT NULL,
  `estadoEdu` VARCHAR(50) NULL DEFAULT NULL,
  `descEdu` VARCHAR(600) NULL DEFAULT NULL,
  `imagenEdu` VARCHAR(100) NULL DEFAULT NULL,
  `persona_id` INT NOT NULL,
  PRIMARY KEY (`idEdu`),
  CONSTRAINT `fk_educacion_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `portfolio`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_educacion_persona1_idx` ON `portfolio`.`educacion` (`persona_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `portfolio`.`habilidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`habilidad` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`habilidad` (
  `idHab` INT NOT NULL,
  `tituloHab` VARCHAR(50) NULL DEFAULT NULL,
  `porcentajeHab` INT NULL DEFAULT NULL,
  `imagenHab` VARCHAR(300) NULL DEFAULT NULL,
  `persona_id` INT NOT NULL,
  PRIMARY KEY (`idHab`),
  CONSTRAINT `fk_habilidad_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `portfolio`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_habilidad_persona1_idx` ON `portfolio`.`habilidad` (`persona_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `portfolio`.`idioma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`idioma` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`idioma` (
  `ididioma` INT NOT NULL,
  `idioma` VARCHAR(100) NULL,
  `nivelIdioma` VARCHAR(50) NULL,
  `persona_id` INT NOT NULL,
  PRIMARY KEY (`ididioma`),
  CONSTRAINT `fk_idioma_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `portfolio`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_idioma_persona1_idx` ON `portfolio`.`idioma` (`persona_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `portfolio`.`proyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`proyecto` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`proyecto` (
  `idProy` INT NOT NULL,
  `tituloProy` VARCHAR(100) NULL,
  `anioProy` INT NULL,
  `descProy` VARCHAR(600) NULL,
  `imagenProy` VARCHAR(300) NULL,
  `persona_id` INT NOT NULL,
  PRIMARY KEY (`idProy`),
  CONSTRAINT `fk_proyecto_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `portfolio`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_proyecto_persona1_idx` ON `portfolio`.`proyecto` (`persona_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `portfolio`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`usuario` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`usuario` (
  `idUsuario` INT NOT NULL,
  `nombreUsuario` VARCHAR(50) NULL,
  `claveUsuario` VARCHAR(20) NULL,
  `permisoUsuario` VARCHAR(20) NULL,
  `persona_id` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  CONSTRAINT `fk_usuario_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `portfolio`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_usuario_persona1_idx` ON `portfolio`.`usuario` (`persona_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
